### ISSUE TITLE
Unity Environment Exception / API Incompatibility

### ISSUE THREAD

**Issue by wschella** [Kinds-of-Intelligence-CFI/animal-ai#22]
Hi

I got the following error with a clean install of the latest version. It happens at the end of the episode. I think I heard something about this before, but just wanted to check if this is expected.

```
Traceback (most recent call last):
  File "/media/Data/PhD/Code/dreamerv3-animalai/aaitest.py", line 48, in <module>
    load_config_and_play(configuration_file=config)
  File "/media/Data/PhD/Code/dreamerv3-animalai/aaitest.py", line 19, in load_config_and_play
    environment = AnimalAIEnvironment(
  File "/media/Data/PhD/Code/dreamerv3-animalai/.env/lib/python3.10/site-packages/animalai/envs/environment.py", line 56, in __init__
    super().__init__(
  File "/media/Data/PhD/Code/dreamerv3-animalai/.env/lib/python3.10/site-packages/mlagents_envs/environment.py", line 151, in __init__
    raise UnityEnvironmentException(
mlagents_envs.exception.UnityEnvironmentException: The communication API version is not compatible between Unity and python. Python API: 0.15.0, Unity API: 1.5.0.
 Please go to https://github.com/Unity-Technologies/ml-agents/releases/tag/latest_release to download the latest version of ML-Agents.
```

Versions
```
animalai=2.0.0
animalai-environment=3.0.2
```

**Comment by wschella** [comment]
The problem is of course using animalai 2.0.0. Please ignore.
